### ISSUE TITLE
Stronger hover effect would be helpful

### ISSUE THREAD

**Issue by ripefig** [psifidotos/latte-indicator-dashtopanel#1]
![Peek 2019-06-19 23-07](https://user-images.githubusercontent.com/45201036/59806509-35e39800-92fd-11e9-8cb7-6c37d8b15b8e.gif)

 On darker panels it's barely visible at all, especially with the parabolic effect.

**Comment by psifidotos** [comment]
I saw your fork, are you interested to add user options for this? I would accept PRs and help you out.

Two options could be used, maxTransparency and transparancyStep both could be percentages with meaningful minimum and max values
