### ISSUE TITLE
Add an option so that the indicator doesnt get its color from app icons

### ISSUE THREAD

**Issue by StarrKiss** [psifidotos/latte-indicator-dashtopanel#2]
![image](https://user-images.githubusercontent.com/13007697/61078301-f254e900-a3e5-11e9-8186-68fdf05dc5b6.png)

As can be seen on the left of this screenshot, it can look messy when two icons of similar colors are next to each other.

**Comment by M0rdecay** [comment]
@StarrKiss, to prevent the indicators from merging, adjust the margins. For example, set margin hight to 20% in Appearance and set indicators lenght to 10%. It will look like this:
![Screenshot_20190729_230356](https://user-images.githubusercontent.com/50422107/62075108-4a4c7600-b255-11e9-9a32-96d4290ee750.png)

**Comment by psifidotos** [comment]
> @StarrKiss, to prevent the indicators from merging, adjust the margins. For example, set margin hight to 20% in Appearance and set indicators lenght to 10%. It will look like this:
> ![Screenshot_20190729_230356](https://user-images.githubusercontent.com/50422107/62075108-4a4c7600-b255-11e9-9a32-96d4290ee750.png)

totally agree, adjusting margins is fixing the mentioned issue
