### ISSUE TITLE
For some icons there is no color, only white

### ISSUE THREAD

**Issue by saligari** [psifidotos/latte-indicator-dashtopanel#3]
Hello,

First of, I love being able to replicate the old unity. However I've run into a weird issue. I don't know how the indicator decides on what color to display, but it seems not to work with some of my icons.

A simple example of an .svg icon that doesn't work: https://pastebin.com/49bFAY1j

Also another icon: https://pastebin.com/s1zRYwqJ

so you can test to see if it replicates. This also happens with the unity indicator.

Thanks again for the great indicator and all!!

The screenshot below illustrates what's happening

![Screenshot_20190807_214933](https://user-images.githubusercontent.com/14283056/62649272-40192e80-b95d-11e9-9180-8c72a1adcf64.png)

**Comment by psifidotos** [comment]
I tested the icons you sent and for the icons you sent the whitish color choice for the background is not problematic. Let me describe you what is happening:

1. Colors for icons are generated from Latte and more specific from function: https://phabricator.kde.org/source/latte-dock/browse/master/liblatte2/iconitem.cpp$429
this code is just the qt version from original Unity code with very minor adjustments 
2. If I have understood the code a bit then the code discovers which color provides the best bright/glowing color and uses that color to produce the final background color
3. For the icons you have sent that color is of course the white one
4. To test out the codepath I used one of your icons and I added in it a green rectangle, you can check it out at: https://pastebin.com/fRsaH6Zp the color produced from Latte was green in the end
5. On the other hand in the screenshot you have sent the background color for firefox icon does not look appropriate. Can you send this icon also to test it out?

**Comment by saligari** [comment]
Hey! Thanks for taking the time to explain it to me! Really appreciate it!

Here's the firefox icon: https://pastebin.com/hGtDtX5v

**Comment by psifidotos** [comment]
Ok, I checked the firefox icon :) you have just found an icon that breaks the Unity approach...

The Unity code computes the r,g,b values and the influence each one has separately... Because the half icon is going to bluish and the other half is going to reddish, and the bluish and reddish are almost exactly the same from contrast point of view number of pixels for each one... the final result is a greyish background color... :)

no idea how this could be improved...
