### ISSUE TITLE
Allow "Max Opacity" to be 0%

### ISSUE THREAD

**Issue by ycardon** [psifidotos/latte-indicator-dashtopanel#4]
Hi, I really like your indicator :)

[edit] I've just realized you also were Latte's developer, I just love your work 

The "Max Opacity" minimum value is 20%. Could you allow it to go to 0% to disable the "active window highlight" functionality ?

Rationale: I've disabled latte's background, and the "active window highlight" leaves a not so pleasant looking "square box" around the icons. I also have other means to know what is my current active window.

**Comment by psifidotos** [comment]
merged
